esphome:
  name: relay-module-light
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

api:
    reboot_timeout: 0s

ota:

web_server:
  port: 80

light:
  - platform: binary
    name: "relay-module-light"
    output: relay_module_light_relay
    id: relay_module_light_light


output:
  - id: relay_module_light_relay
    platform: gpio
    pin: 
      number: GPIO2
      inverted: yes


binary_sensor:
  - platform: gpio
    pin: 
       number: GPIO3
       mode: INPUT_PULLUP
    name: relay_module_light_switch
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_state:
      then:
        - light.toggle: relay_module_light_light

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s
  - platform: uptime
    name: Uptime Sensor
